# Generated by Django 5.1.4 on 2025-01-17 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
