# Generated by Django 5.1.4 on 2025-01-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appt_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
