# Generated by Django 5.1.4 on 2025-02-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
